schema:
	post:
		author: { type: Reference, references: user }
		created: Datetime
		filename: { type: String, length: 255 }
		datastore: { type: String, length: 255 }
	tag:
		name: { type: String, length: 255 }
		parent: { type: Reference, references: tag }
	tagAlias:
		author: { type: Reference, references: user }
		created: Datetime
		alias: { type: String, length: 255 }
		tagId: { type: Reference, references: tag }
	postTag:
		author: { type: Reference, references: user }
		created: Datetime
		tagId: { type: Reference, references: tag }
		postId: { type: Reference, references: post }
	comment:
		author: { type: Reference, references: user }
		created: Datetime
		subject: { type: String, length: 255 }
		body: Text
	user:
		name: { type: String, length: 255 }
